name: near_jsonrpc_client
description: Type-safe Dart client for NEAR Protocol JSON-RPC API. Platform agnostic.
version: 0.1.0
repository: https://github.com/0xJesus/NearFlutter
homepage: https://near.org

environment:
  sdk: ^3.9.0

resolution: workspace

dependencies:
  near_jsonrpc_types:
    path: ../near_jsonrpc_types
  http: ^1.3.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  mockito: ^5.4.5
  build_verify: ^3.1.0
