name: near_jsonrpc_client
description: Type-safe Dart client for NEAR Protocol JSON-RPC API. Works on iOS, Android, Web, Desktop.
version: 0.1.0
homepage: https://0xj.dev
repository: https://github.com/0xjesus/near_jsonrpc_client
issue_tracker: https://github.com/0xjesus/near_jsonrpc_client/issues
topics:
  - near
  - blockchain
  - web3
  - crypto
  - rpc

environment:
  sdk: ^3.9.0

dependencies:
  near_jsonrpc_types: ^0.1.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15
  mockito: ^5.4.5
  build_verify: ^3.1.0
