name: near_wallet_adapter
description: Wallet adapter for NEAR Protocol. Connect wallets, sign and send transactions. WalletConnect & MyNearWallet support.
version: 0.1.0
homepage: https://0xj.dev
repository: https://github.com/0xjesus/near_wallet_adapter
issue_tracker: https://github.com/0xjesus/near_wallet_adapter/issues
topics:
  - near
  - blockchain
  - web3
  - wallet
  - crypto

environment:
  sdk: ^3.9.0

dependencies:
  near_jsonrpc_types: ^0.1.0
  near_jsonrpc_client: ^0.1.0
  equatable: ^2.0.7
  meta: ^1.16.0

dev_dependencies:
  test: ^1.25.8
  mocktail: ^1.0.4
